[project]
name = "dgt-driving-schools-etl"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pandas>=2.3.3",
    "scrapy>=2.13.3",
    "scrapy-selenium>=0.0.7",
    "selenium>=4.38.0",
    "webdriver-manager>=4.0.2",
]
